name: DeployEC2Inscance
on: [workflow_dispatch]
jobs:
  TerraformwillbeinActionsoon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Init
        run: |
         terraform init
        env:
         AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
         AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}
        
      - name: Terraform validate
        run: |
         terraform validate
         ls
      - name: Terraform Apply
        run: |
         terraform apply -auto-approve -var 'personal_access_token=${ secrets.PERSONAL_ACCESS_TOKEN }'
        env:
         AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
         AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}
